name: Daily News
on:
  schedule:
    - cron: '0 23 * * *' # 日本時間 8:00
  workflow_dispatch: # 手動実行用

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install feedparser requests google-generativeai
      - name: Run script
        env:
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
        run: python main.py
